### ISSUE TITLE
INFRA-004: Entity Mapping

### ISSUE THREAD

**Issue by SeanEngineering** [Revenology/traveler#2]
Applies to all entities.

As a user I would like:
- The names of the activities to be stored
- How difficult the activities are (how much energy or time they take)
- What time they occur (if they are time specific)
- The time value for how long the activity is going to take
- The ability to vote (like/dislike) for a plan if to determine
- The ability to make a plan public or private -> May need SQL relationships for this one

As a developer I would like:
- A way to mark an activity if it is to be removed or swapped

https://www.figma.com/file/CODDqp4cLsjkQoFzLCtKNp/Welcome-to-FigJam?type=whiteboard&node-id=0%3A1&t=EhveqAVwnOJrUOeP-1

**Comment by SeanEngineering** [comment]
Hey @jpchaib, I'm going to use your diagram as the scaffolding for the back end work. Hope this is ok with you great job!

**Comment by jpchaib** [comment]
Hi @SeanEngineering , I am honored, please do mate! Do what ever changes you feel like doing as well.

**Comment by SeanEngineering** [comment]
Will be pending on INFRA-008
