### ISSUE TITLE
PROJ-009: BE Signup

### ISSUE THREAD

**Issue by SeanEngineering** [Revenology/traveler#4]
As a user I would like:
- The ability to sign-up for the application
- Have fields to input my name, username, age, email, location

As a developer I would like:
- The ability to check if a user is signed up and reject them if they already exist
- Add a successful user to the database

**Comment by GubbyDuo** [comment]
I've decided to create a User entity for this ticket as I believe it's mandatory. In future, this ticket could probably have been split up.
