### ISSUE TITLE
INFRA-008: Database Setup

### ISSUE THREAD

**Issue by SeanEngineering** [Revenology/traveler#6]
As an engineer/developer I would like:
- Any relationships between entities to be mapped
- The database to be optimised for search features (e.g. friends, posts, destinations)
- A Database creation .sql file that I can run in my local for testing

Depends on INFRA-004

**Comment by SeanEngineering** [comment]
See INFRA-004 for reference of entities

**Comment by GubbyDuo** [comment]
Can we confirm this is being done in PostgreSQL?

**Comment by SeanEngineering** [comment]
Yeah go hard @GubbyDuo
